### PR TITLE
Switch back to noarch

### PR DESCRIPTION
**Pull request by mattwthompson**
I got confused with the `outputs:` syntax in #1 and, along the way, removed `noarch`. This attempts to fix that.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
I don't understand why the array of OS are still being built - for comparison, the `black` feedstock only builds on Linux and I'm using identical syntax AFAICT

https://github.com/conda-forge/black-feedstock/blob/d4b6e4600258557d31c53603ecbd91376dff8826/recipe/meta.yaml

**Comment by jaimergp** [comment]
Always rerender in case of doubt!

@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
Aha, that did the trick!

**Comment by jaimergp** [comment]
Nice. If the local tests are still ok with full `noarch` now, go ahead and merge!

**Review by j-wags — APPROVED** [review]
CMILES is pure python, so from a high level, `noarch` builds should be fine. I won't be able to dedicate time to figuring out the test status until I'm back to work next week so I'll leave it to you to ensure they're passing :-)

**Comment by mattwthompson** [comment]
I'm quickly  double-checking again by installing the tarball from artifacts onto a Linux machine

**Comment by mattwthompson** [comment]
Everything looks good locally (none of these were strictly necessary, but helps me sleep better)

* Installing `noarch/cmiles-base-0.1.6-pyhd8ed1ab_2.tar.bz2` into a minimal-ish fresh environment provides the package, which ...
* Fails to import with no toolkits installed (expected)
* Imports with either toolkit installed
* Works with multiple Python versions 
* Tests passed, run from the unpacked `src_cache/`

**Pull request merged**
